aliyun:
  accesskey: LTAI4GGKT7MSD75swpS6fuhd
  secret: Va6UbTrcb27kRrg6H8u3lAve70BDAw
  sms: 
    signName: 多呗商城
    
spring:
  datasource:
    druid:
      stat-view-servlet:
        login-password: 111111
        login-username: admin
      aop-patterns:
      - com.sourcecode.malls.web.controller.*
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000