aliyun:
  accesskey: LTAIwvOEmE5rhnxS
  secret: XdzLN3mHH1Og83Lx7D7ArVKJshcEJw
  sms: 
    signName: 百士兴科技有限公司
    
spring:
  datasource:
    druid:
      filters: stat  
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 3000