aliyun:
  accesskey: LTAIolH6fF83Q5C2
  secret: ny1CTPPqwfRCKKtTb3rrbgcf4Zr1HX
  sms: 
    signName: 多呗商城
  oss:
    endpoint: oss-cn-zhangjiakou-internal.aliyuncs.com
    privateBucket: mall-private-prod
    publicBucket: mall-public-prod
    
    
remote.server: 172.26.176.62

log.server: ${remote.server}

database:
  host: ${remote.server}

spring:
  datasource:
    druid:
      username: root
      password: "mall!@#"
      stat-view-servlet:
        login-password: 'mall#@!'
        login-username: admin
      aop-patterns:
        - com.sourcecode.malls.web.controller.*
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
       
super-admin:
  username: admin
  password: 'sljj!@#'
  email: feleio@qq.com
        
session:
  redis:
    host: ${remote.server}
    password: "123!@#"
    port: 6379

alipay:
  api:
    url:
      pay:
        notify: 'https://mall-server.bsxkj.com/client/alipay/notify/pay'