aliyun:
  oss:
    endpoint: oss-cn-shenzhen-internal.aliyuncs.com
    privateBucket: mall-template-private-uat
    publicBucket: mall-template-public-uat
    
remote.server: 172.18.132.151

log.server: ${remote.server}

database:
  host: rm-wz9nrd271w892r44t.mysql.rds.aliyuncs.com
  name: mall_uat

spring:
  datasource:
    druid:
      username: mall_uat
      password: "MallMall!@#"
       
super-admin:
  username: admin
  password: 111111
  email: feleio@qq.com
        
session:
  redis:
    host: ${remote.server}
    password: "123!@#"
    port: 6379

alipay:
  api:
    url:
      pay:
        notify: 'https://uat.mall-server.bsxkj.com/client/alipay/notify/pay'