database:
  host: 39.100.158.246
  name: mall_local

spring:
  datasource:
    druid:
      username: root
      password: "mall!@#"
       
super-admin:
  username: admin
  password: 111111
  email: tt@test.com
        
session:
  redis:
    host: localhost
    password: 
    port: 6379
    
aliyun:
  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com
    privateBucket: mall-private-uat
    publicBucket: mall-public-uat
 
alipay:
  api:
    url:
      pay:
        notify:     