database:
  host: localhost

spring:
  datasource:
    druid:
      username: root
      password: 111111
       
super-admin:
  username: admin
  password: '$2a$10$2mx0HIdhHJ.ciiOAqKs7mejYGaeoDiE27.pLGqQCuQ4HYKTTW7twG'
  email: tt@test.com
        
session:
  redis:
    host: localhost
    password: 
    port: 6379
    
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    privateBucket: malls-admin-private-local
    publicBucket: malls-admin-public-local
 
alipay:
  api:
    url:
      pay:
        notify:     