spring:
  jpa:
    open-in-view: false
    show-sql: false
  liquibase:
    enabled: false
  datasource:
    table:
      role: ${spring.datasource.table.prefix}role
      authority: ${spring.datasource.table.prefix}authority
      role_authority: ${spring.datasource.table.prefix}role_authority
      user: ${spring.datasource.table.prefix}user
      user_role: ${spring.datasource.table.prefix}user_role
    druid:
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
      url: jdbc:mysql://${host.database}/malls?useUnicode=true&characterEncoding=utf8
      max-active: 20
      initial-size: 10
      max-wait: 60000
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
       
super-admin:
  code: SUPER_ADMIN
  authority: AUTH_SUPER_ADMIN

default:
  avatar: common/avatar.png
  img: common/img.png

session:
  attributes:
    userId: userId

aliyun:
  region-id: cn-shenzhen   
