aliyun:
  oss:
    endpoint: oss-cn-shenzhen-internal.aliyuncs.com
    privateBucket: mall-private-uat
    publicBucket: mall-public-uat
    
remote.server: 172.26.176.62

log.server: ${remote.server}

database:
  host: ${remote.server}

spring:
  datasource:
    druid:
      username: root
      password: "mall!@#"
       
super-admin:
  username: admin
  password: 'sljj!@#'
  email: feleio@qq.com
        
session:
  redis:
    host: ${remote.server}
    password: "123!@#"
    port: 6379

alipay:
  api:
    url:
      pay:
        notify: 'https://mall-server.bsxkj.com/client/alipay/notify/pay'