database:
  host: localhost

spring:
  datasource:
    druid:
      username: root
      password: 111111
       
super-admin:
  username: admin
  password: 111111
  email: tt@test.com
        
session:
  redis:
    host: localhost
    password: 
    port: 6379
    
aliyun:
  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com
    privateBucket: mall-private-local
    publicBucket: mall-public-local
 
alipay:
  api:
    url:
      pay:
        notify:     